query GetAboutPageData {
  entry(section: "about") {
    slug
    title
    ... on ueberUnsSeite_Entry {
      meilensteine{
        title
        ... on meilenstein_Entry{
          jahr
          beschreibung
        }
      }
      aboutInhalt {
        ... on hero_Entry {
          title
          untertitel
          bild {
            url
          }
        }
        ... on content_Entry {
          title
          untertitel
          text
          bild {
            url
          }
        }
      }
    }
  }
}