query GetEvents($limit: Int = 5){
  entries(section: "veranstaltungen", limit: $limit){
    id
    uid
    title
    slug
    ... on veranstaltung_Entry{
      title
      datum @formatDateTime (format: "d.m.Y")
      kurzbeschreibung
      beschreibung
      bild{
        id
        kind
        title
        folderId
        volumeId
        mimeType
        path
      }
    }
  }
}