query GetStartPageData {
  entry(section: "startseite") {
    title
    ... on startseite_Entry {
      startseitenInhalt {
        ... on hero_Entry {
          title
          untertitel
          bild {
            url
          }
        }
        ... on content_Entry {
          title
          untertitel
          text
          bild {
            url
          }
        }
      }
    }
  }
}
